---
from: H. Sherry Zhang
fromqualifications: BComm (Honours)
fromtitle: PhD student
fromWWW: huizezhangsh.netlify.app
fromemail: Huize.Zhang@monash.edu
fromphone: +61 4 6854 1397
fromsignature: sig.png
toaddress: R Journal
opening: Dear Editor
closing: Regards,
spacing: 1.4
output: monash::letter
---

Please consider our manuscript "Visual Diagnostics for Constrained Optimisation with Application to Guided Tours" for publication in the R Journal.

The manuscript uses visual diagnostic plots to discover deficiencies in the optimisation algorithms of projection pursuit guided tour. We introduce a workflow of collecting data from the optimisation algorithms and using it to produce visual diagnostic plots with a new R package "ferrn". 

In addition, our diagnostic plots provide visual interpretation to the algorithms diagnosed and allow others to understand how different components in the algorithms contribute to the final optimum found. This could inspire software developers to draw more attention to algorithm transparency when designing and implementing new algorithms.

We believe that this manuscript is a good fit to the R Journal.

Thank you for considering this manuscript.
